package dev.ggoggam.inklet

import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

class RoughTest {
    @Test
    fun randomStreamMatchesJavaScriptIncludingUnsignedOverflow() {
        // Golden values generated by the original src/prng.ts with Node.
        val fixtures =
            mapOf(
                0 to listOf(0.26642920868471265, 0.0003297457005828619, 0.2232720274478197, 0.1462021479383111, 0.46732782293111086),
                42 to listOf(0.6011037519201636, 0.44829055899754167, 0.8524657934904099, 0.6697340414393693, 0.17481389874592423),
                -1 to listOf(0.8964226141106337, 0.189478256739676, 0.7156526781618595, 0.9440599093213677, 0.8452364315744489),
            )
        fixtures.forEach { (seed, expected) ->
            val random = Mulberry32(seed)
            assertEquals(expected, List(5) { random.nextDouble() })
        }
    }

    @Test
    fun sameSeedReproducesGeometryAndDifferentSeedChangesIt() {
        fun card(seed: Int) = Rough.roundedRect(0.0, 0.0, 180.0, 48.0, 12.0, RoughOptions(seed))
        assertEquals(card(42), card(42))
        assertNotEquals(card(42), card(43))
    }

    @Test
    fun boilFramesShareTheirBaseSketchAndStayWithinTheRequestedAmplitude() {
        val o = RoughOptions(42, boil = 0.3)
        val base = Rough.line(0.0, 0.0, 120.0, 0.0, o)
        val frames = Rough.variants(o) { Rough.line(0.0, 0.0, 120.0, 0.0, it) }
        assertEquals(3, frames.size)
        assertNotEquals(frames[0], frames[1])
        frames.forEach { strokes ->
            strokes.zip(base).forEach { (actual, original) ->
                actual.points.zip(original.points).forEach { (a, b) ->
                    assertTrue(abs(a.x - b.x) <= 0.3 + 1e-9)
                    assertTrue(abs(a.y - b.y) <= 0.3 + 1e-9)
                }
            }
        }
    }

    @Test
    fun zeroBoilProducesExactlyOneStaticFrame() {
        val frames = Rough.variants(RoughOptions(7, boil = 0.0)) { Rough.circle(20.0, 20.0, 10.0, it) }
        assertEquals(1, frames.size)
    }

    @Test
    fun collapsedControlsHaveNoInvalidPaths() {
        val o = RoughOptions(0)
        assertTrue(Rough.ellipse(0.0, 0.0, 0.0, 0.0, o).isEmpty())
        assertTrue(Rough.roundedRect(0.0, 0.0, -1.0, 20.0, 12.0, o).isEmpty())
        assertTrue(Rough.scribble(0.0, 0.0, 0.0, 12.0, o).isEmpty())
    }

    @Test
    fun tinyCornersAreClampedToFitAndAllShapesStayFinite() {
        val o = RoughOptions(7)
        val shapes =
            Rough.roundedRect(0.0, 0.0, 4.0, 2.0, 200.0, o) +
                Rough.arrow(0.0, 0.0, 0.0, 0.0, o) + Rough.scribble(0.0, 0.0, 1.0, 1.0, o) +
                Rough.checkmark(0.0, 0.0, 24.0, 24.0, o)
        assertTrue(shapes.flatMap { it.points }.all { it.x.isFinite() && it.y.isFinite() })
        assertEquals(2, Rough.roundedRect(0.0, 0.0, 4.0, 2.0, 200.0, o).size)
    }

    @Test
    fun invalidStyleInputsFailEarly() {
        assertFailsWith<IllegalArgumentException> { RoughOptions(0, roughness = -1.0) }
        assertFailsWith<IllegalArgumentException> { RoughOptions(0, boil = Double.NaN) }
        assertFailsWith<IllegalArgumentException> { Rough.sampleLine(0.0, 0.0, 1.0, 1.0, step = 0.0) }
    }
}
